[book]

authors = ["madan maholvi"]
language = "en"
src = "src"
title = "महोलवी नामा "

[output.html]
additional-css = ["css/custom.css"]

cname = "maholvi.shutri.com"
no-section-label = true

[output.html.print]
enable = false    # include support for printable output

